name: Publish

on:
  release:
    types: [created]

jobs:
  build:
    name: Publish
    runs-on: macos-26
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1  #https://github.com/actions/runner-images/blob/main/images/macos/macos-26-Readme.md#xcode
        with:
          xcode-version: '26.5'
      - name: Lint
        run: swift format lint --strict --recursive Sources Tests sample/Sources
      - name: Send Publish Alert
        run: swift run --package-path sample sample --publish
        env:
          APIALERTS_API_KEY: ${{ secrets.APIALERTS_API_KEY }}
