name: Publish
on:
  release:
    types: [created]

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Send Publish Alert
        working-directory: ./GitHubAction
        run: swift build && swift run GitHubAction --publish
        env:
          APIALERTS_API_KEY: ${{ secrets.APIALERTS_API_KEY }}
